# Generated by Django 2.1.4 on 2018-12-16 11:54

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEditSoftware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='软件名字')),
                ('size', models.IntegerField(blank=True, default=0, max_length=50, null=True, verbose_name='软件大小')),
                ('bit', models.IntegerField(blank=True, default=64, max_length=50, null=True, verbose_name='软件位数')),
                ('support_os', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='支持操作系统')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
                ('download_nums', models.IntegerField(default=0, verbose_name='下载量')),
                ('introduce', DjangoUeditor.models.UEditorField(default='', verbose_name='软件简介')),
                ('download_url', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='下载链接')),
                ('net_disk_url', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='网盘链接')),
                ('net_disk_code', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='网盘密码')),
                ('install_introduce', DjangoUeditor.models.UEditorField(default='', verbose_name='安装介绍')),
                ('use_introduce', DjangoUeditor.models.UEditorField(default='', verbose_name='使用介绍')),
            ],
            options={
                'verbose_name': '视频编辑软件',
                'verbose_name_plural': '视频编辑软件',
            },
        ),
    ]
